name: rosetta
description: >-
  Annotation library used to simplify localization
  in Flutter. The library also uses a generator
  dependency called "rosetta_generator".
version: 0.3.0-nullsafety.0
homepage: https://github.com/TeamWanari/rosetta

environment:
  sdk: ">=2.12.0-0 <3.0.0"
