name: rosetta_generator
description: >-
  Generator tool used with Rosetta annotations.
  This generates the helper and delegate classes
  for Flutter localizations.
version: 0.3.0
homepage: https://github.com/TeamWanari/rosetta

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: "^2.0.0"
  source_gen: "^0.9.10+4"
  code_builder: ">3.3.0 <3.8.0"
  dart_style:  "^1.0.0"
  analyzer: "^1.2.0"
  recase: "^4.0.0-nullsafety.0"
  path: ">1.1.2 <1.8.1"
  glob: "^2.0.0"
  rosetta:
    path: ../rosetta/

dev_dependencies:
  build_runner: "^1.12.2"
  