name: Dart CI

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Generate code
      run: pub run build_runner build --delete-conflicting-outputs
    - name: Run tests
      run: pub run test
