name: Dart CI

on:
  push:
    branches: [ stable, development, master ]
  pull_request:
    branches: [ stable, development, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: cd flutter_example && pub get
    - name: Generate code
      run: cd flutter_example && pub run build_runner build --delete-conflicting-outputs
    - name: Run tests
      run: cd flutter_example && pub run test
