name: Dart CI

on:
  push:
    branches: [ stable, development, master ]
  pull_request:
    branches: [ stable, development, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1.3.2
      with:
        flutter-version: '1.17.1'
    - run: cd flutter_example
    - run: flutter pub get
    - run: flutter packages pub run build_runner build --delete-conflicting-outputs
    - run: flutter test
    - run: flutter build apk
